[window]
opacity = 0.8

[font]
size = 12

[font.normal]
family = "UbuntuMono Nerd Font"

[selection]
save_to_clipboard = true

[[keyboard.bindings]]
key = "Equals"
mods = "Control"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "Plus"
mods = "Control|Shift"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "End"
mods = "Shift"
action = "ScrollToBottom"

[[keyboard.bindings]]
key = "Home"
mods = "Shift"
action = "ScrollToTop"

[window.padding]
x = 7
y = 7
